# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/committee", {
  test_that("fec_get_candidate_candidate_id_committees() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_candidate_candidate_id_committees(designation, committee_type, page, filing_frequency, cycle, sort_hide_null, year, sort_nulls_last, sort_null_only, per_page, organization_type, sort, candidate_id)
      test_result
    })
  })

  test_that("fec_get_candidate_candidate_id_committees_history() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_candidate_candidate_id_committees_history(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, candidate_id)
      test_result
    })
  })

  test_that("fec_get_candidate_candidate_id_committees_history_cycle() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_candidate_candidate_id_committees_history_cycle(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, candidate_id, cycle)
      test_result
    })
  })

  test_that("fec_get_committee_committee_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id(designation, committee_type, page, filing_frequency, cycle, sort_hide_null, year, sort_nulls_last, sort_null_only, per_page, organization_type, sort, committee_id)
      test_result
    })
  })

  test_that("fec_get_committee_committee_id_history() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id_history(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, committee_id)
      test_result
    })
  })

  test_that("fec_get_committee_committee_id_history_cycle() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id_history_cycle(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, committee_id, cycle)
      test_result
    })
  })

  test_that("fec_get_committees() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committees(designation, max_first_f1_date, min_first_f1_date, cycle, filing_frequency, sort_nulls_last, sort_hide_null, year, state, sponsor_candidate_id, q, per_page, min_last_f1_date, candidate_id, committee_type, min_first_file_date, page, sort, committee_id, sort_null_only, max_last_f1_date, treasurer_name, organization_type, max_first_file_date, party)
      test_result
    })
  })
})
