# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/receipts", {
  test_that("fec_get_schedules_schedule_a() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a(max_load_date, max_amount, max_image_number, contributor_occupation, recipient_committee_designation, sort_hide_null, is_individual, line_number, contributor_type, recipient_committee_type, per_page, contributor_zip, contributor_city, last_index, last_contribution_receipt_amount, contributor_id, recipient_committee_org_type, contributor_state, sort, two_year_transaction_period, min_date, committee_id, contributor_employer, min_load_date, last_contribution_receipt_date, min_image_number, contributor_name, sort_null_only, image_number, min_amount, max_date)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_employer() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_employer(employer, page, sort_nulls_last, cycle, sort_hide_null, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_occupation() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_occupation(occupation, page, sort_nulls_last, cycle, sort_hide_null, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_size() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_size(sort_nulls_last, page, cycle, sort_hide_null, committee_id, size, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_size_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_size_by_candidate(candidate_id, sort_nulls_last, cycle, page, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_state() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_state(hide_null, page, cycle, state, sort_hide_null, sort_nulls_last, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_state_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_state_by_candidate(candidate_id, sort_nulls_last, cycle, page, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_state_by_candidate_totals() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_state_by_candidate_totals(candidate_id, sort_nulls_last, cycle, page, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_state_totals() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_state_totals(committee_type, cycle, page, state, sort_hide_null, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_by_zip() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_by_zip(page, cycle, zip, sort_hide_null, state, committee_id, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_efile() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_efile(max_amount, contributor_occupation, max_image_number, sort_nulls_last, sort_hide_null, line_number, per_page, contributor_city, contributor_state, page, sort, committee_id, min_date, contributor_employer, contributor_name, min_image_number, sort_null_only, image_number, min_amount, max_date)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_a_sub_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_a_sub_id(max_load_date, max_amount, max_image_number, contributor_occupation, recipient_committee_designation, sort_hide_null, is_individual, line_number, contributor_type, recipient_committee_type, per_page, contributor_zip, contributor_city, last_index, last_contribution_receipt_amount, contributor_id, recipient_committee_org_type, contributor_state, sort, two_year_transaction_period, min_date, committee_id, contributor_employer, min_load_date, last_contribution_receipt_date, min_image_number, contributor_name, sort_null_only, image_number, min_amount, max_date, sub_id)
      test_result
    })
  })
})
