# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/independent_expenditures", {
  test_that("fec_get_schedules_schedule_e() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_e(max_dissemination_date, sort_hide_null, payee_name, q_spender, per_page, last_index, min_dissemination_date, candidate_office_state, filing_form, sort_null_only, max_amount, max_image_number, min_filing_date, cycle, sort_nulls_last, support_oppose_indicator, candidate_office, is_notice, line_number, last_expenditure_amount, last_expenditure_date, candidate_id, last_office_total_ytd, last_support_oppose_indicator, min_date, candidate_party, committee_id, min_image_number, max_filing_date, candidate_office_district, min_amount, image_number, sort, max_date, most_recent)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_e_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_e_by_candidate(office, candidate_id, cycle, district, state, page, support_oppose, election_full, committee_id, sort_hide_null, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_e_efile() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_e_efile(spender_name, min_expenditure_date, sort_nulls_last, max_dissemination_date, support_oppose_indicator, sort_hide_null, candidate_office, is_notice, payee_name, per_page, candidate_search, max_expenditure_amount, min_dissemination_date, min_filed_date, candidate_id, candidate_office_state, max_filed_date, page, min_expenditure_amount, committee_id, candidate_party, max_expenditure_date, filing_form, sort_null_only, candidate_office_district, image_number, sort, most_recent)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_e_totals_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_e_totals_by_candidate(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })
})
