# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/communication_cost", {
  test_that("fec_get_communication_costs() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_communication_costs(max_amount, max_image_number, sort_nulls_last, support_oppose_indicator, sort_hide_null, line_number, per_page, candidate_id, page, min_date, committee_id, min_amount, min_image_number, sort_null_only, image_number, sort, max_date)
      test_result
    })
  })

  test_that("fec_get_communication_costs_aggregates() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_communication_costs_aggregates(candidate_id, page, cycle, support_oppose_indicator, sort_hide_null, sort_nulls_last, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_communication_costs_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_communication_costs_by_candidate(office, candidate_id, cycle, district, state, page, support_oppose, election_full, sort_hide_null, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_communication_costs_totals_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_communication_costs_totals_by_candidate(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })
})
