# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/party_coordinated_expenditures", {
  test_that("fec_get_schedules_schedule_f() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_f(max_amount, max_image_number, cycle, sort_nulls_last, sort_hide_null, line_number, payee_name, per_page, candidate_id, page, min_date, committee_id, min_amount, min_image_number, sort_null_only, image_number, sort, max_date)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_f_sub_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_f_sub_id(per_page, page, sub_id)
      test_result
    })
  })
})
