# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/filings", {
  test_that("fec_get_candidate_candidate_id_filings() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_candidate_candidate_id_filings(office, file_number, form_category, cycle, district, document_type, sort_hide_null, state, amendment_indicator, sort_nulls_last, is_amended, filer_type, max_receipt_date, per_page, primary_general_indicator, request_type, report_year, form_type, committee_type, beginning_image_number, page, sort, min_receipt_date, sort_null_only, q_filer, report_type, party, most_recent, candidate_id)
      test_result
    })
  })

  test_that("fec_get_committee_committee_id_filings() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id_filings(office, file_number, form_category, cycle, district, document_type, sort_hide_null, state, amendment_indicator, sort_nulls_last, is_amended, filer_type, max_receipt_date, per_page, primary_general_indicator, request_type, report_year, form_type, committee_type, beginning_image_number, page, sort, min_receipt_date, sort_null_only, q_filer, report_type, party, most_recent, committee_id)
      test_result
    })
  })

  test_that("fec_get_filings() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_filings(office, file_number, form_category, cycle, district, document_type, sort_hide_null, state, amendment_indicator, sort_nulls_last, is_amended, filer_type, max_receipt_date, per_page, primary_general_indicator, request_type, report_year, form_type, candidate_id, committee_type, beginning_image_number, page, sort, committee_id, min_receipt_date, sort_null_only, q_filer, report_type, party, most_recent)
      test_result
    })
  })

  test_that("fec_get_operations_log() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_operations_log(max_coverage_end_date, sort_nulls_last, amendment_indicator, sort_hide_null, max_receipt_date, per_page, min_transaction_data_complete_date, form_type, max_transaction_data_complete_date, beginning_image_number, page, min_coverage_end_date, sort, min_receipt_date, sort_null_only, candidate_committee_id, report_type, report_year, status_num)
      test_result
    })
  })
})
