# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/disbursements", {
  test_that("fec_get_schedules_schedule_b() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b(disbursement_description, max_amount, max_image_number, image_number, sort_hide_null, last_disbursement_date, line_number, spender_committee_designation, last_disbursement_amount, per_page, last_index, spender_committee_type, sort, two_year_transaction_period, min_date, committee_id, disbursement_purpose_category, recipient_name, recipient_state, recipient_city, min_image_number, spender_committee_org_type, sort_null_only, recipient_committee_id, min_amount, max_date)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_b_by_purpose() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b_by_purpose(purpose, sort_nulls_last, page, cycle, sort_hide_null, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_b_by_recipient() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b_by_recipient(sort_nulls_last, page, cycle, sort_hide_null, committee_id, recipient_name, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_b_by_recipient_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b_by_recipient_id(sort_nulls_last, page, cycle, sort_hide_null, committee_id, sort_null_only, per_page, recipient_id, sort)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_b_efile() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b_efile(disbursement_description, max_amount, page, sort_nulls_last, sort, sort_hide_null, committee_id, min_date, recipient_state, recipient_city, sort_null_only, per_page, image_number, min_amount, max_date)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_b_sub_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_b_sub_id(disbursement_description, max_amount, max_image_number, image_number, sort_hide_null, last_disbursement_date, line_number, spender_committee_designation, last_disbursement_amount, per_page, last_index, spender_committee_type, sort, two_year_transaction_period, min_date, committee_id, disbursement_purpose_category, recipient_name, recipient_state, recipient_city, min_image_number, spender_committee_org_type, sort_null_only, recipient_committee_id, min_amount, max_date, sub_id)
      test_result
    })
  })
})
