# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/presidential", {
  test_that("fec_get_presidential_contributions_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_presidential_contributions_by_candidate(contributor_state, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_presidential_contributions_by_size() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_presidential_contributions_by_size(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, size, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_presidential_contributions_by_state() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_presidential_contributions_by_state(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_presidential_coverage_end_date() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_presidential_coverage_end_date(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_presidential_financial_summary() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_presidential_financial_summary(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort)
      test_result
    })
  })
})
