# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/efiling", {
  test_that("fec_get_efile_filings() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_efile_filings(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort)
      test_result
    })
  })

  test_that("fec_get_efile_reports_house_senate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_efile_reports_house_senate(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort)
      test_result
    })
  })

  test_that("fec_get_efile_reports_pac_party() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_efile_reports_pac_party(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort)
      test_result
    })
  })

  test_that("fec_get_efile_reports_presidential() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_efile_reports_presidential(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort)
      test_result
    })
  })
})
