# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/electioneering", {
  test_that("fec_get_electioneering() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_electioneering(candidate_id, max_amount, sort_nulls_last, page, sort_hide_null, committee_id, min_date, min_amount, per_page, sort_null_only, description, sort, report_year, last_index, max_date)
      test_result
    })
  })

  test_that("fec_get_electioneering_aggregates() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_electioneering_aggregates(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, committee_id, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_electioneering_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_electioneering_by_candidate(office, candidate_id, cycle, district, state, page, sort_hide_null, election_full, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_electioneering_totals_by_candidate() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_electioneering_totals_by_candidate(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, election_full, sort_null_only, per_page, sort)
      test_result
    })
  })
})
