# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/financial", {
  test_that("fec_get_committee_committee_id_reports() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id_reports(min_debts_owed_amount, max_disbursements_amount, max_total_contributions, max_debts_owed_expenditures, cycle, sort_nulls_last, sort_hide_null, year, max_receipts_amount, max_cash_on_hand_end_period_amount, is_amended, min_disbursements_amount, max_party_coordinated_expenditures, per_page, max_independent_expenditures, min_receipts_amount, min_party_coordinated_expenditures, candidate_id, beginning_image_number, page, type, sort, min_total_contributions, min_cash_on_hand_end_period_amount, sort_null_only, min_independent_expenditures, report_type, committee_id)
      test_result
    })
  })

  test_that("fec_get_committee_committee_id_totals() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_committee_committee_id_totals(cycle, sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, committee_id)
      test_result
    })
  })

  test_that("fec_get_elections() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_elections(office, page, district, state, cycle, sort_hide_null, election_full, sort_nulls_last, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_elections_search() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_elections_search(office, cycle, district, zip, state, sort_hide_null, sort_nulls_last, page, sort_null_only, per_page, sort)
      test_result
    })
  })

  test_that("fec_get_elections_summary() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_elections_summary(office, cycle, district, state, election_full)
      test_result
    })
  })

  test_that("fec_get_reports_entity_type() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_reports_entity_type(min_debts_owed_amount, max_debts_owed_expenditures, sort_hide_null, year, max_cash_on_hand_end_period_amount, filer_type, max_party_coordinated_expenditures, q_spender, max_receipt_date, per_page, max_independent_expenditures, min_party_coordinated_expenditures, committee_type, page, min_total_contributions, min_cash_on_hand_end_period_amount, min_receipt_date, sort_null_only, min_independent_expenditures, q_filer, max_disbursements_amount, max_total_contributions, cycle, amendment_indicator, sort_nulls_last, max_receipts_amount, is_amended, min_disbursements_amount, min_receipts_amount, candidate_id, beginning_image_number, sort, committee_id, report_type, most_recent, entity_type)
      test_result
    })
  })

  test_that("fec_get_totals_by_entity() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_totals_by_entity(cycle, sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page)
      test_result
    })
  })

  test_that("fec_get_totals_entity_type() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_totals_entity_type(max_first_f1_date, min_receipts, cycle, filing_frequency, max_receipts, sort_hide_null, sort_nulls_last, min_last_debts_owed_by_committee, max_last_cash_on_hand_end_period, treasurer_name, sponsor_candidate_id, per_page, max_disbursements, committee_state, committee_type, page, max_last_debts_owed_by_committee, committee_id, committee_designation, sort_null_only, min_first_f1_date, organization_type, sort, min_disbursements, min_last_cash_on_hand_end_period, entity_type)
      test_result
    })
  })
})
