# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/loans", {
  test_that("fec_get_schedules_schedule_c() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_c(min_incurred_date, candidate_name, max_amount, max_image_number, sort_nulls_last, sort_hide_null, line_number, max_incurred_date, per_page, last_index, loan_source_name, page, sort, max_payment_to_date, min_payment_to_date, committee_id, min_image_number, sort_null_only, image_number, min_amount)
      test_result
    })
  })

  test_that("fec_get_schedules_schedule_c_sub_id() returns expected result", {
    expect_snapshot({
      test_result <- fec_get_schedules_schedule_c_sub_id(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, sub_id)
      test_result
    })
  })
})
