# These functions were generated by the {beekeeper} package, based on
# components@security_schemes from the source API description. You may want to
# delete unused options. In addition, APIs often have additional security
# options that are not formally documented in the API description. For example,
# for any `location = query` `api_key` options, it might be possible to instead
# pass the same parameter in a header, possibly with a different name. Consult
# the text description of authentication in your API documentation.

fec_security <- function(req, api_key) {
  req <- fec_security_api_key_header_auth(req, api_key)
  return(req)
}

# An API key provided by the API provider. This key is not clearly documented in
# the API description. Check the API documentation for details.
fec_security_api_key_header_auth <- function(req, api_key) {
  nectar::security_api_key(
    req,
    location = "header",
    parameter_name = "X-Api-Key",
    api_key = api_key
  )
}
