# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get electioneering
#'
#' An electioneering communication is any broadcast, cable or satellite communication that fulfills each of the following conditions: _The communication refers to a clearly identified federal candidate._ _The communication is publicly distributed by a television station, radio station, cable television system or satellite system for a fee._ _The communication is distributed within 60 days prior to a general election or 30 days prior to a primary election to federal office._
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param max_amount Filter for all amounts less than a value.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_date Minimum disbursement date
#' @param min_amount Filter for all amounts greater than a value.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param description BKTODO: No description provided.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param report_year Forms with coverage date - year from the coverage ending date. Forms without coverage date - year from the receipt date.
#' @param last_index Index of last result from previous page
#' @param max_date Maximum disbursement date
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_electioneering <- function(candidate_id, max_amount, sort_nulls_last, page, sort_hide_null, committee_id, min_date, min_amount, per_page, sort_null_only, description, sort, report_year, last_index, max_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/electioneering/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, max_amount = max_amount, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, committee_id = committee_id, min_date = min_date, min_amount = min_amount, per_page = per_page, sort_null_only = sort_null_only, description = description, sort = sort, report_year = report_year, last_index = last_index, max_date = max_date)
  )
}

#' Get electioneering aggregates
#'
#' Electioneering communications costs aggregates
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_electioneering_aggregates <- function(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, committee_id, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/electioneering/aggregates/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, cycle = cycle, sort_hide_null = sort_hide_null, committee_id = committee_id, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get electioneering by candidate
#'
#' Electioneering costs aggregated by candidate
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param state US state or territory where a candidate runs for office
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_electioneering_by_candidate <- function(office, candidate_id, cycle, district, state, page, sort_hide_null, election_full, sort_nulls_last, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/electioneering/by_candidate/",
    method = "get",
    api_key = api_key,
    query = list(office = office, candidate_id = candidate_id, cycle = cycle, district = district, state = state, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_nulls_last = sort_nulls_last, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get electioneering totals by candidate
#'
#' Total electioneering communications spent on candidates by cycle or candidate election year
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_electioneering_totals_by_candidate <- function(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, election_full, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/electioneering/totals/by_candidate/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, cycle = cycle, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}
