# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get efile filings
#'
#' Basic information about electronic files coming into the FEC, posted as they are received.
#'
#' @inheritParams fec_call_api
#' @param file_number Filing ID number
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_receipt_date Selects all filings received after this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_receipt_date Selects all filings received before this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param q_filer Keyword search for filer name or ID
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_efile_filings <- function(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/efile/filings/",
    method = "get",
    api_key = api_key,
    query = list(file_number = file_number, sort_nulls_last = sort_nulls_last, page = page, per_page = per_page, sort_hide_null = sort_hide_null, committee_id = committee_id, min_receipt_date = min_receipt_date, max_receipt_date = max_receipt_date, q_filer = q_filer, sort_null_only = sort_null_only, sort = sort)
  )
}

#' Get efile reports house senate
#'
#' Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports. Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended. DISCLAIMER: The field labels contained within this resource are subject to change. We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users.
#'
#' @inheritParams fec_call_api
#' @param file_number Filing ID number
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_receipt_date Selects all filings received after this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_receipt_date Selects all filings received before this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param q_filer Keyword search for filer name or ID
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_efile_reports_house_senate <- function(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/efile/reports/house-senate/",
    method = "get",
    api_key = api_key,
    query = list(file_number = file_number, sort_nulls_last = sort_nulls_last, page = page, per_page = per_page, sort_hide_null = sort_hide_null, committee_id = committee_id, min_receipt_date = min_receipt_date, max_receipt_date = max_receipt_date, q_filer = q_filer, sort_null_only = sort_null_only, sort = sort)
  )
}

#' Get efile reports pac party
#'
#' Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports. Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended. DISCLAIMER: The field labels contained within this resource are subject to change. We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users.
#'
#' @inheritParams fec_call_api
#' @param file_number Filing ID number
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_receipt_date Selects all filings received after this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_receipt_date Selects all filings received before this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param q_filer Keyword search for filer name or ID
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_efile_reports_pac_party <- function(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/efile/reports/pac-party/",
    method = "get",
    api_key = api_key,
    query = list(file_number = file_number, sort_nulls_last = sort_nulls_last, page = page, per_page = per_page, sort_hide_null = sort_hide_null, committee_id = committee_id, min_receipt_date = min_receipt_date, max_receipt_date = max_receipt_date, q_filer = q_filer, sort_null_only = sort_null_only, sort = sort)
  )
}

#' Get efile reports presidential
#'
#' Key financial data reported periodically by committees as they are reported. This feed includes summary information from the the House F3 reports, the presidential F3p reports and the PAC and party F3x reports. Generally, committees file reports on a quarterly or monthly basis, but some must also submit a report 12 days before primary elections. Therefore, during the primary season, the period covered by this file may be different for different committees. These totals also incorporate any changes made by committees, if any report covering the period is amended. DISCLAIMER: The field labels contained within this resource are subject to change. We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users.
#'
#' @inheritParams fec_call_api
#' @param file_number Filing ID number
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_receipt_date Selects all filings received after this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_receipt_date Selects all filings received before this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param q_filer Keyword search for filer name or ID
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_efile_reports_presidential <- function(file_number, sort_nulls_last, page, per_page, sort_hide_null, committee_id, min_receipt_date, max_receipt_date, q_filer, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/efile/reports/presidential/",
    method = "get",
    api_key = api_key,
    query = list(file_number = file_number, sort_nulls_last = sort_nulls_last, page = page, per_page = per_page, sort_hide_null = sort_hide_null, committee_id = committee_id, min_receipt_date = min_receipt_date, max_receipt_date = max_receipt_date, q_filer = q_filer, sort_null_only = sort_null_only, sort = sort)
  )
}
