# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get legal search
#'
#' Search legal documents by document type, or across all document types using keywords, parameter values and ranges.
#'
#' @inheritParams fec_call_api
#' @param hits_returned Number of results to return (max 10)
#' @param af_report_year Admin fine report year
#' @param case_max_open_date The latest date opened of case
#' @param ao_max_issue_date Latest issue date of advisory opinion
#' @param case_statutory_citation Statutory citations
#' @param case_respondents Cases respondents
#' @param q Text to search legal documents for
#' @param ao_min_issue_date Earliest issue date of advisory opinion
#' @param af_max_fd_date The latest Final Determination date
#' @param from_hit Get results starting from this index
#' @param af_fd_fine_amount Final Determination fine amount
#' @param type Legal Document type to refine search by - statutes - regulations - advisory_opinions - murs - admin_fines
#' @param af_name Admin fine committee name
#' @param ao_requestor_type Code of the advisory opinion requestor type.
#' @param ao_statutory_citation Statutory citations
#' @param ao_entity_name Name of commenter or representative
#' @param mur_type Type of MUR : current or archived
#' @param ao_regulatory_citation Regulatory citations
#' @param af_committee_id Admin fine committee ID
#' @param ao_requestor The requestor of the advisory opinion
#' @param case_citation_require_all Require all citations to be in document (default behavior is any)
#' @param af_min_fd_date The earliest Final Determination date
#' @param ao_is_pending AO is pending
#' @param af_rtb_fine_amount Reason to Believe fine amount
#' @param case_election_cycles Cases election cycles
#' @param ao_category Category of the document
#' @param ao_citation_require_all Require all citations to be in document (default behavior is any)
#' @param case_dispositions Cases dispositions
#' @param af_max_rtb_date The latest Reason to Believe date
#' @param case_min_open_date The earliest date opened of case
#' @param case_max_close_date The latest date closed of case
#' @param ao_min_request_date Earliest request date of advisory opinion
#' @param ao_status Status of AO (pending, withdrawn, or final)
#' @param case_doc_category_id Select one or more case_doc_category_id to filter by corresponding CASE_DOCUMENT_CATEGORY: - 1 - Conciliation Agreements - 2 - Complaint, Responses, Designation of Counsel and Extensions of Timee - 3 - General Counsel Reports, Briefs, Notifications and Responses - 4 - Certifications - 5 - Civil Penalties, Disgorgements and Other Payments - 6 - Statements of Reasons
#' @param af_min_rtb_date The earliest Reason to Believe date
#' @param ao_name Force advisory opinion name
#' @param case_regulatory_citation Regulatory citations
#' @param ao_no Force advisory opinion number
#' @param case_min_close_date The earliest date closed of case
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param ao_max_request_date Latest request date of advisory opinion
#' @param case_no Enforcement matter case number
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_legal_search <- function(hits_returned, af_report_year, case_max_open_date, ao_max_issue_date, case_statutory_citation, case_respondents, q, ao_min_issue_date, af_max_fd_date, from_hit, af_fd_fine_amount, type, af_name, ao_requestor_type, ao_statutory_citation, ao_entity_name, mur_type, ao_regulatory_citation, af_committee_id, ao_requestor, case_citation_require_all, af_min_fd_date, ao_is_pending, af_rtb_fine_amount, case_election_cycles, ao_category, ao_citation_require_all, case_dispositions, af_max_rtb_date, case_min_open_date, case_max_close_date, ao_min_request_date, ao_status, case_doc_category_id, af_min_rtb_date, ao_name, case_regulatory_citation, ao_no, case_min_close_date, sort, ao_max_request_date, case_no, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/legal/search/",
    method = "get",
    api_key = api_key,
    query = list(hits_returned = hits_returned, af_report_year = af_report_year, case_max_open_date = case_max_open_date, ao_max_issue_date = ao_max_issue_date, case_statutory_citation = case_statutory_citation, case_respondents = case_respondents, q = q, ao_min_issue_date = ao_min_issue_date, af_max_fd_date = af_max_fd_date, from_hit = from_hit, af_fd_fine_amount = af_fd_fine_amount, type = type, af_name = af_name, ao_requestor_type = ao_requestor_type, ao_statutory_citation = ao_statutory_citation, ao_entity_name = ao_entity_name, mur_type = mur_type, ao_regulatory_citation = ao_regulatory_citation, af_committee_id = af_committee_id, ao_requestor = ao_requestor, case_citation_require_all = case_citation_require_all, af_min_fd_date = af_min_fd_date, ao_is_pending = ao_is_pending, af_rtb_fine_amount = af_rtb_fine_amount, case_election_cycles = case_election_cycles, ao_category = ao_category, ao_citation_require_all = ao_citation_require_all, case_dispositions = case_dispositions, af_max_rtb_date = af_max_rtb_date, case_min_open_date = case_min_open_date, case_max_close_date = case_max_close_date, ao_min_request_date = ao_min_request_date, ao_status = ao_status, case_doc_category_id = case_doc_category_id, af_min_rtb_date = af_min_rtb_date, ao_name = ao_name, case_regulatory_citation = case_regulatory_citation, ao_no = ao_no, case_min_close_date = case_min_close_date, sort = sort, ao_max_request_date = ao_max_request_date, case_no = case_no)
  )
}
