# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get presidential contributions by candidate
#'
#' Net receipts per candidate. Filter with `contributor_state='US'` for national totals
#'
#' @inheritParams fec_call_api
#' @param contributor_state State of contributor
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_presidential_contributions_by_candidate <- function(contributor_state, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/presidential/contributions/by_candidate/",
    method = "get",
    api_key = api_key,
    query = list(contributor_state = contributor_state, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get presidential contributions by size
#'
#' Contribution receipts by size per candidate. Filter by candidate_id, election_year and/or size
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. -P00000001 All candidates -P00000002 Democrasts -P00000003 Republicans
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Year of election
#' @param size The total all contributions in the following ranges: ``` -0 $200 and under -200 $200.01 - $499.99 -500 $500 - $999.99 -1000 $1000 - $1999.99 -2000 $2000 + ``` Unitemized contributions are included in the `0` category.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_presidential_contributions_by_size <- function(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, size, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/presidential/contributions/by_size/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, size = size, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get presidential contributions by state
#'
#' Contribution receipts by state per candidate. Filter by candidate_id and/or election_year
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. -P00000001 All candidates -P00000002 Democrasts -P00000003 Republicans
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_presidential_contributions_by_state <- function(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/presidential/contributions/by_state/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get presidential coverage end date
#'
#' Coverage end date per candidate. Filter by candidate_id and/or election_year
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. -P00000001 All candidates -P00000002 Democrasts -P00000003 Republicans
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_presidential_coverage_end_date <- function(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/presidential/coverage_end_date/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get presidential financial summary
#'
#' Financial summary per candidate. Filter by candidate_id and/or election_year
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. -P00000001 All candidates -P00000002 Democrasts -P00000003 Republicans
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_presidential_financial_summary <- function(candidate_id, sort_nulls_last, page, sort_hide_null, election_year, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/presidential/financial_summary/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}
