# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get communication costs
#'
#' 52 U.S.C. 30118 allows &quot;communications by a corporation to its stockholders and executive or administrative personnel and their families or by a labor organization to its members and their families on any subject,&quot; including the express advocacy of the election or defeat of any Federal candidate. The costs of such communications must be reported to the Federal Election Commission under certain circumstances.
#'
#' @inheritParams fec_call_api
#' @param max_amount Filter for all amounts less than a value.
#' @param max_image_number Maxium image number of the page where the schedule item is reported
#' @param sort_nulls_last Toggle that sorts null values last
#' @param support_oppose_indicator Support or opposition
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param line_number Filter for form and line number using the following format: `FORM-LINENUMBER`. For example an argument such as `F3X-16` would filter down to all entries from form `F3X` line number `16`.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page For paginating through results, starting at page 1
#' @param min_date Minimum date
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_amount Filter for all amounts greater than a value.
#' @param min_image_number Minium image number of the page where the schedule item is reported
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param image_number An unique identifier for each page where the electronic or paper filing is reported.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param max_date Maximum date
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_communication_costs <- function(max_amount, max_image_number, sort_nulls_last, support_oppose_indicator, sort_hide_null, line_number, per_page, candidate_id, page, min_date, committee_id, min_amount, min_image_number, sort_null_only, image_number, sort, max_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/communication_costs/",
    method = "get",
    api_key = api_key,
    query = list(max_amount = max_amount, max_image_number = max_image_number, sort_nulls_last = sort_nulls_last, support_oppose_indicator = support_oppose_indicator, sort_hide_null = sort_hide_null, line_number = line_number, per_page = per_page, candidate_id = candidate_id, page = page, min_date = min_date, committee_id = committee_id, min_amount = min_amount, min_image_number = min_image_number, sort_null_only = sort_null_only, image_number = image_number, sort = sort, max_date = max_date)
  )
}

#' Get communication costs aggregates
#'
#' Communication cost aggregated by candidate ID and committee ID.
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page For paginating through results, starting at page 1
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param support_oppose_indicator Support or opposition
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort_nulls_last Toggle that sorts null values last
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_communication_costs_aggregates <- function(candidate_id, page, cycle, support_oppose_indicator, sort_hide_null, sort_nulls_last, committee_id, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/communication_costs/aggregates/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, page = page, cycle = cycle, support_oppose_indicator = support_oppose_indicator, sort_hide_null = sort_hide_null, sort_nulls_last = sort_nulls_last, committee_id = committee_id, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get communication costs by candidate
#'
#' Communication cost aggregated by candidate ID and committee ID.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param state US state or territory where a candidate runs for office
#' @param page For paginating through results, starting at page 1
#' @param support_oppose Support or opposition
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_communication_costs_by_candidate <- function(office, candidate_id, cycle, district, state, page, support_oppose, election_full, sort_hide_null, sort_nulls_last, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/communication_costs/by_candidate/",
    method = "get",
    api_key = api_key,
    query = list(office = office, candidate_id = candidate_id, cycle = cycle, district = district, state = state, page = page, support_oppose = support_oppose, election_full = election_full, sort_hide_null = sort_hide_null, sort_nulls_last = sort_nulls_last, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get communication costs totals by candidate
#'
#' Total communications costs aggregated across committees on supported or opposed candidates by cycle or candidate election year.
#'
#' @inheritParams fec_call_api
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_communication_costs_totals_by_candidate <- function(candidate_id, sort_nulls_last, page, cycle, sort_hide_null, election_full, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/communication_costs/totals/by_candidate/",
    method = "get",
    api_key = api_key,
    query = list(candidate_id = candidate_id, sort_nulls_last = sort_nulls_last, page = page, cycle = cycle, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}
