# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get schedules schedule f
#'
#' Schedule F, it shows all special expenditures a national or state party committee makes in connection with the general election campaigns of federal candidates. These coordinated party expenditures do not count against the contribution limits but are subject to other limits, these limits are detailed in Chapter 7 of the FEC Campaign Guide for Political Party Committees.
#'
#' @inheritParams fec_call_api
#' @param max_amount Filter for all amounts less than a value.
#' @param max_image_number Maxium image number of the page where the schedule item is reported
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param line_number Filter for form and line number using the following format: `FORM-LINENUMBER`. For example an argument such as `F3X-16` would filter down to all entries from form `F3X` line number `16`.
#' @param payee_name BKTODO: No description provided.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page For paginating through results, starting at page 1
#' @param min_date Minimum date
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_amount Filter for all amounts greater than a value.
#' @param min_image_number Minium image number of the page where the schedule item is reported
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param image_number An unique identifier for each page where the electronic or paper filing is reported.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param max_date Maximum date
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_schedules_schedule_f <- function(max_amount, max_image_number, cycle, sort_nulls_last, sort_hide_null, line_number, payee_name, per_page, candidate_id, page, min_date, committee_id, min_amount, min_image_number, sort_null_only, image_number, sort, max_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/schedules/schedule_f/",
    method = "get",
    api_key = api_key,
    query = list(max_amount = max_amount, max_image_number = max_image_number, cycle = cycle, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, line_number = line_number, payee_name = payee_name, per_page = per_page, candidate_id = candidate_id, page = page, min_date = min_date, committee_id = committee_id, min_amount = min_amount, min_image_number = min_image_number, sort_null_only = sort_null_only, image_number = image_number, sort = sort, max_date = max_date)
  )
}

#' Get schedules schedule f sub id
#'
#' Schedule F, it shows all special expenditures a national or state party committee makes in connection with the general election campaigns of federal candidates. These coordinated party expenditures do not count against the contribution limits but are subject to other limits, these limits are detailed in Chapter 7 of the FEC Campaign Guide for Political Party Committees.
#'
#' @inheritParams fec_call_api
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param page For paginating through results, starting at page 1
#' @param sub_id BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_schedules_schedule_f_sub_id <- function(per_page, page, sub_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/schedules/schedule_f/{sub_id}/", sub_id = sub_id),
    method = "get",
    api_key = api_key,
    query = list(per_page = per_page, page = page)
  )
}
