# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get schedules schedule d
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#'
#' @inheritParams fec_call_api
#' @param creditor_debtor_name BKTODO: No description provided.
#' @param max_image_number Maxium image number of the page where the schedule item is reported
#' @param sort_nulls_last Toggle that sorts null values last
#' @param max_amount_outstanding_beginning BKTODO: No description provided.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param min_payment_period BKTODO: No description provided.
#' @param max_amount_incurred BKTODO: No description provided.
#' @param nature_of_debt BKTODO: No description provided.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_amount_outstanding_close BKTODO: No description provided.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page For paginating through results, starting at page 1
#' @param min_date Minimum load date
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_amount_outstanding_close BKTODO: No description provided.
#' @param max_payment_period BKTODO: No description provided.
#' @param min_image_number Minium image number of the page where the schedule item is reported
#' @param min_amount_incurred BKTODO: No description provided.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param image_number An unique identifier for each page where the electronic or paper filing is reported.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param min_amount_outstanding_beginning BKTODO: No description provided.
#' @param max_date Maximum load date
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_schedules_schedule_d <- function(creditor_debtor_name, max_image_number, sort_nulls_last, max_amount_outstanding_beginning, sort_hide_null, min_payment_period, max_amount_incurred, nature_of_debt, per_page, max_amount_outstanding_close, candidate_id, page, min_date, committee_id, min_amount_outstanding_close, max_payment_period, min_image_number, min_amount_incurred, sort_null_only, image_number, sort, min_amount_outstanding_beginning, max_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/schedules/schedule_d/",
    method = "get",
    api_key = api_key,
    query = list(creditor_debtor_name = creditor_debtor_name, max_image_number = max_image_number, sort_nulls_last = sort_nulls_last, max_amount_outstanding_beginning = max_amount_outstanding_beginning, sort_hide_null = sort_hide_null, min_payment_period = min_payment_period, max_amount_incurred = max_amount_incurred, nature_of_debt = nature_of_debt, per_page = per_page, max_amount_outstanding_close = max_amount_outstanding_close, candidate_id = candidate_id, page = page, min_date = min_date, committee_id = committee_id, min_amount_outstanding_close = min_amount_outstanding_close, max_payment_period = max_payment_period, min_image_number = min_image_number, min_amount_incurred = min_amount_incurred, sort_null_only = sort_null_only, image_number = image_number, sort = sort, min_amount_outstanding_beginning = min_amount_outstanding_beginning, max_date = max_date)
  )
}

#' Get schedules schedule d sub id
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param page For paginating through results, starting at page 1
#' @param sub_id BKTODO: No description provided.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_schedules_schedule_d_sub_id <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, sub_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/schedules/schedule_d/{sub_id}/", sub_id = sub_id),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, page = page)
  )
}
