# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get candidate candidate id committees
#'
#' This endpoint is useful for finding detailed information about a particular committee or filer. Use the `committee_id` to find the most recent information about the committee.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param page For paginating through results, starting at page 1
#' @param filing_frequency The one-letter code of the filing frequency: - A Administratively terminated - D Debt - M Monthly filer - Q Quarterly filer - T Terminated - W Waived
#' @param cycle A two year election cycle that the committee was active- (after original registration date but before expiration date in Form 1s) The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year A year that the committee was active— (after original registration date or filing but before expiration date)
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param organization_type The one-letter code for the kind for organization: - C corporation - L labor organization - M membership organization - T trade association - V cooperative - W corporation without capital stock
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_committees <- function(designation, committee_type, page, filing_frequency, cycle, sort_hide_null, year, sort_nulls_last, sort_null_only, per_page, organization_type, sort, candidate_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/committees/", candidate_id = candidate_id),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, committee_type = committee_type, page = page, filing_frequency = filing_frequency, cycle = cycle, sort_hide_null = sort_hide_null, year = year, sort_nulls_last = sort_nulls_last, sort_null_only = sort_null_only, per_page = per_page, organization_type = organization_type, sort = sort)
  )
}

#' Get candidate candidate id committees history
#'
#' Explore a filer's characteristics over time. This can be particularly useful if the committees change treasurers, designation, or `committee_type`.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_committees_history <- function(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, candidate_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/committees/history/", candidate_id = candidate_id),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get candidate candidate id committees history cycle
#'
#' Explore a filer's characteristics over time. This can be particularly useful if the committees change treasurers, designation, or `committee_type`.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param cycle A two year election cycle that the committee was active- (after original registration date but before expiration date in Form 1s) The cycle begins with an odd year and is named for its ending, even year.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_committees_history_cycle <- function(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, candidate_id, cycle, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/committees/history/{cycle}/", candidate_id = candidate_id, cycle = cycle),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get committee committee id
#'
#' This endpoint is useful for finding detailed information about a particular committee or filer. Use the `committee_id` to find the most recent information about the committee.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param page For paginating through results, starting at page 1
#' @param filing_frequency The one-letter code of the filing frequency: - A Administratively terminated - D Debt - M Monthly filer - Q Quarterly filer - T Terminated - W Waived
#' @param cycle A two year election cycle that the committee was active- (after original registration date but before expiration date in Form 1s) The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year A year that the committee was active— (after original registration date or filing but before expiration date)
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param organization_type The one-letter code for the kind for organization: - C corporation - L labor organization - M membership organization - T trade association - V cooperative - W corporation without capital stock
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id <- function(designation, committee_type, page, filing_frequency, cycle, sort_hide_null, year, sort_nulls_last, sort_null_only, per_page, organization_type, sort, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, committee_type = committee_type, page = page, filing_frequency = filing_frequency, cycle = cycle, sort_hide_null = sort_hide_null, year = year, sort_nulls_last = sort_nulls_last, sort_null_only = sort_null_only, per_page = per_page, organization_type = organization_type, sort = sort)
  )
}

#' Get committee committee id history
#'
#' Explore a filer's characteristics over time. This can be particularly useful if the committees change treasurers, designation, or `committee_type`.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_history <- function(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/history/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get committee committee id history cycle
#'
#' Explore a filer's characteristics over time. This can be particularly useful if the committees change treasurers, designation, or `committee_type`.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param cycle A two year election cycle that the committee was active- (after original registration date but before expiration date in Form 1s) The cycle begins with an odd year and is named for its ending, even year.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_history_cycle <- function(designation, sort_nulls_last, page, sort_hide_null, election_full, sort_null_only, per_page, sort, committee_id, cycle, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/history/{cycle}/", committee_id = committee_id, cycle = cycle),
    method = "get",
    api_key = api_key,
    query = list(designation = designation, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get committees
#'
#' Fetch basic information about committees and filers. Use parameters to filter for particular characteristics.
#'
#' @inheritParams fec_call_api
#' @param designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param max_first_f1_date Filter for committees whose first Form 1 was received on or before this date.
#' @param min_first_f1_date Filter for committees whose first Form 1 was received on or after this date.
#' @param cycle A two year election cycle that the committee was active- (after original registration date but before expiration date in Form 1s) The cycle begins with an odd year and is named for its ending, even year.
#' @param filing_frequency The one-letter code of the filing frequency: - A Administratively terminated - D Debt - M Monthly filer - Q Quarterly filer - T Terminated - W Waived
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year A year that the committee was active— (after original registration date or filing but before expiration date)
#' @param state US state or territory
#' @param sponsor_candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. This is a filter for Leadership PAC sponsor.
#' @param q The name of the committee. If a committee changes its name, the most recent name will be shown. Committee names are not unique. Use committee_id for looking up records.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param min_last_f1_date Filter for committees whose latest Form 1 was received on or after this date.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param min_first_file_date Filter for committees whose first filing was received on or after this date.
#' @param page For paginating through results, starting at page 1
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param max_last_f1_date Filter for committees whose latest Form 1 was received on or before this date.
#' @param treasurer_name Name of the Committee's treasurer. If multiple treasurers for the committee, the most recent treasurer will be shown.
#' @param organization_type The one-letter code for the kind for organization: - C corporation - L labor organization - M membership organization - T trade association - V cooperative - W corporation without capital stock
#' @param max_first_file_date Filter for committees whose first filing was received on or before this date.
#' @param party Three-letter code for the party affiliated with a candidate or committee. For example, DEM for Democratic Party and REP for Republican Party.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committees <- function(designation, max_first_f1_date, min_first_f1_date, cycle, filing_frequency, sort_nulls_last, sort_hide_null, year, state, sponsor_candidate_id, q, per_page, min_last_f1_date, candidate_id, committee_type, min_first_file_date, page, sort, committee_id, sort_null_only, max_last_f1_date, treasurer_name, organization_type, max_first_file_date, party, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/committees/",
    method = "get",
    api_key = api_key,
    query = list(designation = designation, max_first_f1_date = max_first_f1_date, min_first_f1_date = min_first_f1_date, cycle = cycle, filing_frequency = filing_frequency, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, year = year, state = state, sponsor_candidate_id = sponsor_candidate_id, q = q, per_page = per_page, min_last_f1_date = min_last_f1_date, candidate_id = candidate_id, committee_type = committee_type, min_first_file_date = min_first_file_date, page = page, sort = sort, committee_id = committee_id, sort_null_only = sort_null_only, max_last_f1_date = max_last_f1_date, treasurer_name = treasurer_name, organization_type = organization_type, max_first_file_date = max_first_file_date, party = party)
  )
}
