# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get candidate candidate id
#'
#' This endpoint is useful for finding detailed information about a particular
#' candidate. Use the `candidate_id` to find the most recent information about
#' that candidate.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_status One-letter code explaining if the candidate is: - C
#'   present candidate - F future candidate - N not yet a candidate - P prior
#'   candidate
#' @param cycle Two-year election cycle in which a candidate runs for office.
#'   Calculated from Form 2. The cycle begins with an odd year and is named for
#'   its ending, even year. This cycle follows the traditional house election
#'   cycle and subdivides the presidential and Senate elections into comparable
#'   two-year blocks. To retrieve data for the entire four years of a
#'   presidential term or six years of a senatorial term, you will need the
#'   `election_full` flag.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param state US state or territory where a candidate runs for office
#' @param district Two-digit US House distirict of the office the candidate is
#'   running for. Presidential, Senate and House at-large candidates will have
#'   District 00.
#' @param year Retrieve records pertaining to a particular election year. The
#'   list of election years is based on a candidate filing a statement of
#'   candidacy (F2) for that year.
#' @param name Name (candidate or committee) to search for. Alias for 'q'.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param federal_funds_flag A boolean the describes if a presidential candidate
#'   has accepted federal funds. The flag will be false for House and Senate
#'   candidates.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param page For paginating through results, starting at page 1
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param has_raised_funds A boolean that describes if a candidate's committee
#'   has ever received any receipts for their campaign for this particular
#'   office. (Candidates have separate candidate IDs for each office.)
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column
#'   that is non-null
#' @param incumbent_challenge One-letter code ('I', 'C', 'O') explaining if the
#'   candidate is an incumbent, a challenger, or if the seat is open.
#' @param party Three-letter code for the party affiliated with a candidate or
#'   committee. For example, DEM for Democratic Party and REP for Republican
#'   Party.
#' @param candidate_id A unique identifier assigned to each candidate registered
#'   with the FEC. If a person runs for several offices, that person will have
#'   separate candidate IDs for each office.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id <- function(office,
                                           candidate_status,
                                           cycle,
                                           sort_nulls_last,
                                           state,
                                           district,
                                           year,
                                           name,
                                           sort_hide_null,
                                           federal_funds_flag,
                                           per_page,
                                           page,
                                           sort,
                                           has_raised_funds,
                                           election_year,
                                           sort_null_only,
                                           incumbent_challenge,
                                           party,
                                           candidate_id,
                                           api_key = Sys.getenv(
                                             "FEC_API_KEY",
                                             unset = "DEMO_KEY"
                                           )) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/", candidate_id = candidate_id),
    method = "get",
    api_key = api_key,
    query = list(
      office = office,
      candidate_status = candidate_status,
      cycle = cycle,
      sort_nulls_last = sort_nulls_last,
      state = state,
      district = district,
      year = year,
      name = name,
      sort_hide_null = sort_hide_null,
      federal_funds_flag = federal_funds_flag,
      per_page = per_page,
      page = page,
      sort = sort,
      has_raised_funds = has_raised_funds,
      election_year = election_year,
      sort_null_only = sort_null_only,
      incumbent_challenge = incumbent_challenge,
      party = party
    )
  )
}

#' Get candidate candidate id history
#'
#' Find out a candidate's characteristics over time. This is particularly useful if the candidate runs for the same office in different districts or you want to know more about a candidate's previous races. This information is organized by `candidate_id`, so it won't help you find a candidate who ran for different offices over time; candidates get a new ID for each office.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param page For paginating through results, starting at page 1
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_history <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, election_full, page, candidate_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/history/", candidate_id = candidate_id),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, election_full = election_full, page = page)
  )
}

#' Get candidate candidate id history cycle
#'
#' Find out a candidate's characteristics over time. This is particularly useful if the candidate runs for the same office in different districts or you want to know more about a candidate's previous races. This information is organized by `candidate_id`, so it won't help you find a candidate who ran for different offices over time; candidates get a new ID for each office.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param page For paginating through results, starting at page 1
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_history_cycle <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, election_full, page, candidate_id, cycle, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/history/{cycle}/", candidate_id = candidate_id, cycle = cycle),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, election_full = election_full, page = page)
  )
}

#' Get candidate candidate id totals
#'
#' This endpoint provides information about a committee's Form 3, Form 3X, or Form 3P financial reports, which are aggregated by two-year period. We refer to two-year periods as a `cycle`. The cycle is named after the even-numbered year and includes the year before it. To obtain totals from 2013 and 2014, you would use 2014. In odd-numbered years, the current cycle is the next year — for example, in 2015, the current cycle is 2016. For presidential and Senate candidates, multiple two-year cycles exist between elections.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidate_candidate_id_totals <- function(sort_nulls_last, cycle, page, sort_hide_null, election_full, sort_null_only, per_page, sort, candidate_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/candidate/{candidate_id}/totals/", candidate_id = candidate_id),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, cycle = cycle, page = page, sort_hide_null = sort_hide_null, election_full = election_full, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get candidates
#'
#' Fetch basic information about candidates, and use parameters to filter
#' results to the candidates you're looking for. Each result reflects a unique
#' FEC candidate ID. That ID is particular to the candidate for a particular
#' office sought. If a candidate runs for the same office multiple times, the ID
#' stays the same. If the same person runs for another office — for example, a
#' House candidate runs for a Senate office — that candidate will get a unique
#' ID for each office.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_status One-letter code explaining if the candidate is: - C
#'   present candidate - F future candidate - N not yet a candidate - P prior
#'   candidate
#' @param cycle Two-year election cycle in which a candidate runs for office.
#'   Calculated from Form 2. The cycle begins with an odd year and is named for
#'   its ending, even year. This cycle follows the traditional house election
#'   cycle and subdivides the presidential and Senate elections into comparable
#'   two-year blocks. To retrieve data for the entire four years of a
#'   presidential term or six years of a senatorial term, you will need the
#'   `election_full` flag.
#' @param district Two-digit US House distirict of the office the candidate is
#'   running for. Presidential, Senate and House at-large candidates will have
#'   District 00.
#' @param year Retrieve records pertaining to a particular election year. The
#'   list of election years is based on a candidate filing a statement of
#'   candidacy (F2) for that year.
#' @param state US state or territory where a candidate runs for office
#' @param is_active_candidate Candidates who are actively seeking office. If no
#'   value is specified, all candidates are returned. When True is specified,
#'   only active candidates are returned. When False is specified, only inactive
#'   candidates are returned.
#' @param name Name of candidate running for office
#' @param federal_funds_flag A boolean the describes if a presidential candidate
#'   has accepted federal funds. The flag will be false for House and Senate
#'   candidates.
#' @param candidate_id A unique identifier assigned to each candidate registered
#'   with the FEC. If a person runs for several offices, that person will have
#'   separate candidate IDs for each office.
#' @param min_first_file_date Selects all candidates whose first filing was
#'   received by the FEC after this date.
#' @param has_raised_funds A boolean that describes if a candidate's committee
#'   has ever received any receipts for their campaign for this particular
#'   office. (Candidates have separate candidate IDs for each office.)
#' @param election_year Year of election
#' @param incumbent_challenge One-letter code ('I', 'C', 'O') explaining if the
#'   candidate is an incumbent, a challenger, or if the seat is open.
#' @param max_first_file_date Selects all candidates whose first filing was
#'   received by the FEC before this date.
#' @param party Three-letter code for the party affiliated with a candidate or
#'   committee. For example, DEM for Democratic Party and REP for Republican
#'   Party.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates <- function(office = NULL,
                               candidate_status = NULL,
                               cycle = NULL,
                               district = NULL,
                               year = NULL,
                               state = NULL,
                               name = NULL,
                               is_active_candidate = NULL,
                               federal_funds_flag = NULL,
                               candidate_id = NULL,
                               min_first_file_date = NULL,
                               has_raised_funds = NULL,
                               election_year = NULL,
                               incumbent_challenge = NULL,
                               max_first_file_date = NULL,
                               party = NULL,
                               api_key = Sys.getenv(
                                 "FEC_API_KEY",
                                 unset = "DEMO_KEY"
                               )) {
  fec_call_api(
    path = "/candidates/",
    method = "get",
    api_key = api_key,
    query = list(
      office = office,
      candidate_status = candidate_status,
      cycle = cycle,
      district = district,
      year = year,
      state = state,
      name = name,
      is_active_candidate = is_active_candidate,
      federal_funds_flag = federal_funds_flag,
      candidate_id = candidate_id,
      min_first_file_date = min_first_file_date,
      page = page,
      sort = sort,
      has_raised_funds = has_raised_funds,
      election_year = election_year,
      incumbent_challenge = incumbent_challenge,
      max_first_file_date = max_first_file_date,
      party = party
    )
  )
}

#' Get candidates search
#'
#' Fetch basic information about candidates and their principal committees. Each result reflects a unique FEC candidate ID. That ID is assigned to the candidate for a particular office sought. If a candidate runs for the same office over time, that ID stays the same. If the same person runs for multiple offices — for example, a House candidate runs for a Senate office — that candidate will get a unique ID for each office. The candidate endpoints primarily use data from FEC registration [Form 1](https://www.fec.gov/pdf/forms/fecfrm1.pdf) for committee information and [Form 2](https://www.fec.gov/pdf/forms/fecfrm2.pdf) for candidate information.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_status One-letter code explaining if the candidate is: - C present candidate - F future candidate - N not yet a candidate - P prior candidate
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year Retrieve records pertaining to a particular election year. The list of election years is based on a candidate filing a statement of candidacy (F2) for that year.
#' @param state US state or territory where a candidate runs for office
#' @param name Name (candidate or committee) to search for. Alias for 'q'.
#' @param is_active_candidate Candidates who are actively seeking office. If no value is specified, all candidates are returned. When True is specified, only active candidates are returned. When False is specified, only inactive candidates are returned.
#' @param q Name of candidate running for office
#' @param federal_funds_flag A boolean the describes if a presidential candidate has accepted federal funds. The flag will be false for House and Senate candidates.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param min_first_file_date Selects all candidates whose first filing was received by the FEC after this date.
#' @param page For paginating through results, starting at page 1
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param has_raised_funds A boolean that describes if a candidate's committee has ever received any receipts for their campaign for this particular office. (Candidates have separate candidate IDs for each office.)
#' @param election_year Year of election
#' @param incumbent_challenge One-letter code ('I', 'C', 'O') explaining if the candidate is an incumbent, a challenger, or if the seat is open.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param max_first_file_date Selects all candidates whose first filing was received by the FEC before this date.
#' @param party Three-letter code for the party affiliated with a candidate or committee. For example, DEM for Democratic Party and REP for Republican Party.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates_search <- function(office, candidate_status, cycle, district, sort_nulls_last, sort_hide_null, year, state, name, is_active_candidate, q, federal_funds_flag, per_page, candidate_id, min_first_file_date, page, sort, has_raised_funds, election_year, incumbent_challenge, sort_null_only, max_first_file_date, party, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/candidates/search/",
    method = "get",
    api_key = api_key,
    query = list(office = office, candidate_status = candidate_status, cycle = cycle, district = district, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, year = year, state = state, name = name, is_active_candidate = is_active_candidate, q = q, federal_funds_flag = federal_funds_flag, per_page = per_page, candidate_id = candidate_id, min_first_file_date = min_first_file_date, page = page, sort = sort, has_raised_funds = has_raised_funds, election_year = election_year, incumbent_challenge = incumbent_challenge, sort_null_only = sort_null_only, max_first_file_date = max_first_file_date, party = party)
  )
}

#' Get candidates totals
#'
#' Aggregated candidate receipts and disbursements grouped by cycle.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param min_receipts Minimum aggregated receipts
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param district District of candidate
#' @param max_receipts Maximum aggregated receipts
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param state State of candidate
#' @param max_debts_owed_by_committee Maximum debt
#' @param sort_nulls_last Toggle that sorts null values last
#' @param min_debts_owed_by_committee Minimum debt
#' @param is_active_candidate Candidates who are actively seeking office. If no value is specified, all candidates are returned. When True is specified, only active candidates are returned. When False is specified, only inactive candidates are returned.
#' @param q Name of candidate running for office
#' @param federal_funds_flag A boolean the describes if a presidential candidate has accepted federal funds. The flag will be false for House and Senate candidates.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_cash_on_hand_end_period Maximum cash on hand
#' @param max_disbursements Maximum aggregated disbursements
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page For paginating through results, starting at page 1
#' @param has_raised_funds A boolean that describes if a candidate's committee has ever received any receipts for their campaign for this particular office. (Candidates have separate candidate IDs for each office.)
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param election_year Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param min_cash_on_hand_end_period Minimum cash on hand
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param party Three-letter party code
#' @param min_disbursements Minimum aggregated disbursements
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates_totals <- function(office, min_receipts, cycle, district, max_receipts, sort_hide_null, state, max_debts_owed_by_committee, sort_nulls_last, min_debts_owed_by_committee, is_active_candidate, q, federal_funds_flag, per_page, max_cash_on_hand_end_period, max_disbursements, candidate_id, page, has_raised_funds, election_full, election_year, sort_null_only, min_cash_on_hand_end_period, sort, party, min_disbursements, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/candidates/totals/",
    method = "get",
    api_key = api_key,
    query = list(office = office, min_receipts = min_receipts, cycle = cycle, district = district, max_receipts = max_receipts, sort_hide_null = sort_hide_null, state = state, max_debts_owed_by_committee = max_debts_owed_by_committee, sort_nulls_last = sort_nulls_last, min_debts_owed_by_committee = min_debts_owed_by_committee, is_active_candidate = is_active_candidate, q = q, federal_funds_flag = federal_funds_flag, per_page = per_page, max_cash_on_hand_end_period = max_cash_on_hand_end_period, max_disbursements = max_disbursements, candidate_id = candidate_id, page = page, has_raised_funds = has_raised_funds, election_full = election_full, election_year = election_year, sort_null_only = sort_null_only, min_cash_on_hand_end_period = min_cash_on_hand_end_period, sort = sort, party = party, min_disbursements = min_disbursements)
  )
}

#' Get candidates totals aggregates
#'
#' Candidate total receipts and disbursements aggregated by `aggregate_by`.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param sort_nulls_last Toggle that sorts null values last
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param state US state or territory where a candidate runs for office
#' @param min_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param is_active_candidate Candidates who are actively seeking office. If no value is specified, all candidates are returned. When True is specified, only active candidates are returned. When False is specified, only inactive candidates are returned.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param aggregate_by Candidate totals aggregate_by (Chose one of dropdown options): - ' ' grouped by election year - office grouped by election year, by office - office-state grouped by election year, by office, by state - office-state-district grouped by election year, by office, by state, by district - office-party grouped by election year, by office, by party
#' @param page For paginating through results, starting at page 1
#' @param election_year Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param party Three-letter code for the party affiliated with a candidate or committee. For example, DEM for Democratic Party and REP for Republican Party.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates_totals_aggregates <- function(office, sort_nulls_last, district, state, min_election_cycle, sort_hide_null, is_active_candidate, per_page, max_election_cycle, aggregate_by, page, election_year, election_full, sort_null_only, sort, party, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/candidates/totals/aggregates/",
    method = "get",
    api_key = api_key,
    query = list(office = office, sort_nulls_last = sort_nulls_last, district = district, state = state, min_election_cycle = min_election_cycle, sort_hide_null = sort_hide_null, is_active_candidate = is_active_candidate, per_page = per_page, max_election_cycle = max_election_cycle, aggregate_by = aggregate_by, page = page, election_year = election_year, election_full = election_full, sort_null_only = sort_null_only, sort = sort, party = party)
  )
}

#' Get candidates totals by office
#'
#' Aggregated candidate receipts and disbursements grouped by office by cycle.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param min_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param is_active_candidate Candidates who are actively seeking office. If no value is specified, all candidates are returned. When True is specified, only active candidates are returned. When False is specified, only inactive candidates are returned.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_election_cycle Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates_totals_by_office <- function(office, sort_nulls_last, page, min_election_cycle, sort_hide_null, election_year, election_full, is_active_candidate, sort_null_only, per_page, max_election_cycle, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/candidates/totals/by_office/",
    method = "get",
    api_key = api_key,
    query = list(office = office, sort_nulls_last = sort_nulls_last, page = page, min_election_cycle = min_election_cycle, sort_hide_null = sort_hide_null, election_year = election_year, election_full = election_full, is_active_candidate = is_active_candidate, sort_null_only = sort_null_only, per_page = per_page, max_election_cycle = max_election_cycle, sort = sort)
  )
}

#' Get candidates totals by office by party
#'
#' Aggregated candidate receipts and disbursements grouped by office by party by cycle.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_year Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param is_active_candidate Candidates who are actively seeking office. If no value is specified, all candidates are returned. When True is specified, only active candidates are returned. When False is specified, only inactive candidates are returned.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_candidates_totals_by_office_by_party <- function(office, sort_nulls_last, page, sort_hide_null, election_year, election_full, is_active_candidate, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/candidates/totals/by_office/by_party/",
    method = "get",
    api_key = api_key,
    query = list(office = office, sort_nulls_last = sort_nulls_last, page = page, sort_hide_null = sort_hide_null, election_year = election_year, election_full = election_full, is_active_candidate = is_active_candidate, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get committee committee id candidates
#'
#' This endpoint is useful for finding detailed information about a particular candidate. Use the `candidate_id` to find the most recent information about that candidate.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param candidate_status One-letter code explaining if the candidate is: - C present candidate - F future candidate - N not yet a candidate - P prior candidate
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param state US state or territory where a candidate runs for office
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param year Retrieve records pertaining to a particular election year. The list of election years is based on a candidate filing a statement of candidacy (F2) for that year.
#' @param name Name (candidate or committee) to search for. Alias for 'q'.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param federal_funds_flag A boolean the describes if a presidential candidate has accepted federal funds. The flag will be false for House and Senate candidates.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param page For paginating through results, starting at page 1
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param has_raised_funds A boolean that describes if a candidate's committee has ever received any receipts for their campaign for this particular office. (Candidates have separate candidate IDs for each office.)
#' @param election_year Year of election
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param incumbent_challenge One-letter code ('I', 'C', 'O') explaining if the candidate is an incumbent, a challenger, or if the seat is open.
#' @param party Three-letter code for the party affiliated with a candidate or committee. For example, DEM for Democratic Party and REP for Republican Party.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_candidates <- function(office, candidate_status, cycle, sort_nulls_last, state, district, year, name, sort_hide_null, federal_funds_flag, per_page, page, sort, has_raised_funds, election_year, sort_null_only, incumbent_challenge, party, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/candidates/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(office = office, candidate_status = candidate_status, cycle = cycle, sort_nulls_last = sort_nulls_last, state = state, district = district, year = year, name = name, sort_hide_null = sort_hide_null, federal_funds_flag = federal_funds_flag, per_page = per_page, page = page, sort = sort, has_raised_funds = has_raised_funds, election_year = election_year, sort_null_only = sort_null_only, incumbent_challenge = incumbent_challenge, party = party)
  )
}

#' Get committee committee id candidates history
#'
#' Find out a candidate's characteristics over time. This is particularly useful if the candidate runs for the same office in different districts or you want to know more about a candidate's previous races. This information is organized by `candidate_id`, so it won't help you find a candidate who ran for different offices over time; candidates get a new ID for each office.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param page For paginating through results, starting at page 1
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_candidates_history <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, election_full, page, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/candidates/history/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, election_full = election_full, page = page)
  )
}

#' Get committee committee id candidates history cycle
#'
#' Find out a candidate's characteristics over time. This is particularly useful if the candidate runs for the same office in different districts or you want to know more about a candidate's previous races. This information is organized by `candidate_id`, so it won't help you find a candidate who ran for different offices over time; candidates get a new ID for each office.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param page For paginating through results, starting at page 1
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_candidates_history_cycle <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, election_full, page, committee_id, cycle, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/candidates/history/{cycle}/", committee_id = committee_id, cycle = cycle),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, election_full = election_full, page = page)
  )
}
