# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get names candidates
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#'
#' @inheritParams fec_call_api
#' @param q Name (candidate or committee) to search for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_names_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/names/candidates/",
    method = "get",
    api_key = api_key,
    query = list(q = q)
  )
}

#' Get names committees
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#'
#' @inheritParams fec_call_api
#' @param q Name (candidate or committee) to search for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_names_committees <- function(q, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/names/committees/",
    method = "get",
    api_key = api_key,
    query = list(q = q)
  )
}
