# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get rad analyst
#'
#' Use this endpoint to look up the RAD Analyst for a committee. The mission of the Reports Analysis Division (RAD) is to ensure that campaigns and political committees file timely and accurate reports that fully disclose their financial activities. RAD is responsible for reviewing statements and financial reports filed by political committees participating in federal elections, providing assistance and guidance to the committees to properly file their reports, and for taking appropriate action to ensure compliance with the Federal Election Campaign Act (FECA).
#'
#' @inheritParams fec_call_api
#' @param min_assignment_update_date Filter results for assignment updates made after this date
#' @param max_assignment_update_date Filter results for assignment updates made before this date
#' @param analyst_short_id Short ID of RAD analyst
#' @param email Email of RAD analyst
#' @param page For paginating through results, starting at page 1
#' @param sort_nulls_last Toggle that sorts null values last
#' @param title Title of RAD analyst
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param name Name of RAD analyst
#' @param telephone_ext Telephone extension of RAD analyst
#' @param analyst_id ID of RAD analyst
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_rad_analyst <- function(min_assignment_update_date, max_assignment_update_date, analyst_short_id, email, page, sort_nulls_last, title, sort_hide_null, committee_id, name, telephone_ext, analyst_id, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/rad-analyst/",
    method = "get",
    api_key = api_key,
    query = list(min_assignment_update_date = min_assignment_update_date, max_assignment_update_date = max_assignment_update_date, analyst_short_id = analyst_short_id, email = email, page = page, sort_nulls_last = sort_nulls_last, title = title, sort_hide_null = sort_hide_null, committee_id = committee_id, name = name, telephone_ext = telephone_ext, analyst_id = analyst_id, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get state election office
#'
#' State laws and procedures govern elections for state or local offices as well as how candidates appear on election ballots. Contact the appropriate state election office for more information.
#'
#' @inheritParams fec_call_api
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param state Enter a state (Ex: AK, TX, VA etc..) to find the local election offices contact information.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param page For paginating through results, starting at page 1
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_state_election_office <- function(sort_null_only, sort_nulls_last, per_page, state, sort_hide_null, sort, page, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/state-election-office/",
    method = "get",
    api_key = api_key,
    query = list(sort_null_only = sort_null_only, sort_nulls_last = sort_nulls_last, per_page = per_page, state = state, sort_hide_null = sort_hide_null, sort = sort, page = page)
  )
}
