# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get committee committee id reports
#'
#' Each report represents the summary information from Form 3, Form 3X and Form 3P. These reports have key statistics that illuminate the financial status of a given committee. Things like cash on hand, debts owed by committee, total receipts, and total disbursements are especially helpful for understanding a committee's financial dealings. By default, this endpoint includes both amended and final versions of each report. To restrict to only the final versions of each report, use `is_amended=false`; to retrieve only reports that have been amended, use `is_amended=true`. Several different reporting structures exist, depending on the type of organization that submits financial information. To see an example of these reporting requirements, look at the summary and detailed summary pages of Form 3, Form 3X, and Form 3P. DISCLAIMER: The field labels contained within this resource are subject to change. We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users.
#'
#' @inheritParams fec_call_api
#' @param min_debts_owed_amount Filter for all amounts greater than a value.
#' @param max_disbursements_amount Filter for all amounts less than a value.
#' @param max_total_contributions Filter for all amounts less than a value.
#' @param max_debts_owed_expenditures Filter for all amounts less than a value.
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year Forms with coverage date - year from the coverage ending date. Forms without coverage date - year from the receipt date.
#' @param max_receipts_amount Filter for all amounts less than a value.
#' @param max_cash_on_hand_end_period_amount Filter for all amounts less than a value.
#' @param is_amended False indicates that a report is the most recent. True indicates that the report has been superseded by an amendment.
#' @param min_disbursements_amount Filter for all amounts greater than a value.
#' @param max_party_coordinated_expenditures Filter for all amounts less than a value.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_independent_expenditures Filter for all amounts less than a value.
#' @param min_receipts_amount Filter for all amounts greater than a value.
#' @param min_party_coordinated_expenditures Filter for all amounts greater than a value.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param beginning_image_number Unique identifier for the electronic or paper report. This number is used to construct PDF URLs to the original document.
#' @param page For paginating through results, starting at page 1
#' @param type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param min_total_contributions Filter for all amounts greater than a value.
#' @param min_cash_on_hand_end_period_amount Filter for all amounts greater than a value.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param min_independent_expenditures Filter for all amounts greater than a value.
#' @param report_type Report type; prefix with "-" to exclude. Name of report where the underlying data comes from: - 10D Pre-Election - 10G Pre-General - 10P Pre-Primary - 10R Pre-Run-Off - 10S Pre-Special - 12C Pre-Convention - 12G Pre-General - 12P Pre-Primary - 12R Pre-Run-Off - 12S Pre-Special - 30D Post-Election - 30G Post-General - 30P Post-Primary - 30R Post-Run-Off - 30S Post-Special - 60D Post-Convention - M1 January Monthly - M10 October Monthly - M11 November Monthly - M12 December Monthly - M2 February Monthly - M3 March Monthly - M4 April Monthly - M5 May Monthly - M6 June Monthly - M7 July Monthly - M8 August Monthly - M9 September Monthly - MY Mid-Year Report - Q1 April Quarterly - Q2 July Quarterly - Q3 October Quarterly - TER Termination Report - YE Year-End - ADJ COMP ADJUST AMEND - CA COMPREHENSIVE AMEND
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_reports <- function(min_debts_owed_amount, max_disbursements_amount, max_total_contributions, max_debts_owed_expenditures, cycle, sort_nulls_last, sort_hide_null, year, max_receipts_amount, max_cash_on_hand_end_period_amount, is_amended, min_disbursements_amount, max_party_coordinated_expenditures, per_page, max_independent_expenditures, min_receipts_amount, min_party_coordinated_expenditures, candidate_id, beginning_image_number, page, type, sort, min_total_contributions, min_cash_on_hand_end_period_amount, sort_null_only, min_independent_expenditures, report_type, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/reports/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(min_debts_owed_amount = min_debts_owed_amount, max_disbursements_amount = max_disbursements_amount, max_total_contributions = max_total_contributions, max_debts_owed_expenditures = max_debts_owed_expenditures, cycle = cycle, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, year = year, max_receipts_amount = max_receipts_amount, max_cash_on_hand_end_period_amount = max_cash_on_hand_end_period_amount, is_amended = is_amended, min_disbursements_amount = min_disbursements_amount, max_party_coordinated_expenditures = max_party_coordinated_expenditures, per_page = per_page, max_independent_expenditures = max_independent_expenditures, min_receipts_amount = min_receipts_amount, min_party_coordinated_expenditures = min_party_coordinated_expenditures, candidate_id = candidate_id, beginning_image_number = beginning_image_number, page = page, type = type, sort = sort, min_total_contributions = min_total_contributions, min_cash_on_hand_end_period_amount = min_cash_on_hand_end_period_amount, sort_null_only = sort_null_only, min_independent_expenditures = min_independent_expenditures, report_type = report_type)
  )
}

#' Get committee committee id totals
#'
#' This endpoint provides information about a committee's Form 3, Form 3X, or Form 3P financial reports, which are aggregated by two-year period. We refer to two-year periods as a `cycle`. The cycle is named after the even-numbered year and includes the year before it. To obtain totals from 2013 and 2014, you would use 2014. In odd-numbered years, the current cycle is the next year — for example, in 2015, the current cycle is 2016. For presidential and Senate candidates, multiple two-year cycles exist between elections.
#'
#' @inheritParams fec_call_api
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param page For paginating through results, starting at page 1
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_committee_committee_id_totals <- function(cycle, sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, committee_id, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/committee/{committee_id}/totals/", committee_id = committee_id),
    method = "get",
    api_key = api_key,
    query = list(cycle = cycle, sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, page = page)
  )
}

#' Get elections
#'
#' Look at the top-level financial information for all candidates running for the same office. Choose a 2-year cycle, and `house`, `senate` or `presidential`. If you are looking for a Senate seat, you will need to select the state using a two-letter abbreviation. House races require state and a two-digit district number. Since this endpoint reflects financial information, it will only have candidates once they file financial reporting forms. Query the `/candidates` endpoint to retrieve an-up-to-date list of all the candidates that filed to run for a particular seat.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param page For paginating through results, starting at page 1
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param state US state or territory where a candidate runs for office
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_elections <- function(office, page, district, state, cycle, sort_hide_null, election_full, sort_nulls_last, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/elections/",
    method = "get",
    api_key = api_key,
    query = list(office = office, page = page, district = district, state = state, cycle = cycle, sort_hide_null = sort_hide_null, election_full = election_full, sort_nulls_last = sort_nulls_last, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get elections search
#'
#' List elections by cycle, office, state, and district.
#'
#' @inheritParams fec_call_api
#' @param office BKTODO: No description provided.
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param zip Zip code
#' @param state US state or territory where a candidate runs for office
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_elections_search <- function(office, cycle, district, zip, state, sort_hide_null, sort_nulls_last, page, sort_null_only, per_page, sort, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/elections/search/",
    method = "get",
    api_key = api_key,
    query = list(office = office, cycle = cycle, district = district, zip = zip, state = state, sort_hide_null = sort_hide_null, sort_nulls_last = sort_nulls_last, page = page, sort_null_only = sort_null_only, per_page = per_page, sort = sort)
  )
}

#' Get elections summary
#'
#' List elections by cycle, office, state, and district.
#'
#' @inheritParams fec_call_api
#' @param office Federal office candidate runs for: H, S or P
#' @param cycle Two-year election cycle in which a candidate runs for office. Calculated from Form 2. The cycle begins with an odd year and is named for its ending, even year. This cycle follows the traditional house election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. To retrieve data for the entire four years of a presidential term or six years of a senatorial term, you will need the `election_full` flag.
#' @param district Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.
#' @param state US state or territory where a candidate runs for office
#' @param election_full `True` indicates that full election period of a candidate. `False` indicates that two year election cycle.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_elections_summary <- function(office, cycle, district, state, election_full, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/elections/summary/",
    method = "get",
    api_key = api_key,
    query = list(office = office, cycle = cycle, district = district, state = state, election_full = election_full)
  )
}

#' Get reports entity type
#'
#' Each report represents the summary information from Form 3, Form 3X and Form 3P. These reports have key statistics that illuminate the financial status of a given committee. Things like cash on hand, debts owed by committee, total receipts, and total disbursements are especially helpful for understanding a committee's financial dealings. By default, this endpoint includes both amended and final versions of each report. To restrict to only the final versions of each report, use `is_amended=false`; to retrieve only reports that have been amended, use `is_amended=true`. Several different reporting structures exist, depending on the type of organization that submits financial information. To see an example of these reporting requirements, look at the summary and detailed summary pages of Form 3, Form 3X, and Form 3P. DISCLAIMER: The field labels contained within this resource are subject to change. We are attempting to succinctly label these fields while conveying clear meaning to ensure accessibility for all users.
#'
#' @inheritParams fec_call_api
#' @param min_debts_owed_amount Filter for all amounts greater than a value.
#' @param max_debts_owed_expenditures Filter for all amounts less than a value.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param year Forms with coverage date - year from the coverage ending date. Forms without coverage date - year from the receipt date.
#' @param max_cash_on_hand_end_period_amount Filter for all amounts less than a value.
#' @param filer_type The method used to file with the FEC, either electronic or on paper.
#' @param max_party_coordinated_expenditures Filter for all amounts less than a value.
#' @param q_spender Keyword search for spender name or ID
#' @param max_receipt_date Selects all items received by FEC before this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_independent_expenditures Filter for all amounts less than a value.
#' @param min_party_coordinated_expenditures Filter for all amounts greater than a value.
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param page For paginating through results, starting at page 1
#' @param min_total_contributions Filter for all amounts greater than a value.
#' @param min_cash_on_hand_end_period_amount Filter for all amounts greater than a value.
#' @param min_receipt_date Selects all items received by FEC after this date(MM/DD/YYYY or YYYY-MM-DD)
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param min_independent_expenditures Filter for all amounts greater than a value.
#' @param q_filer Keyword search for filer name or ID
#' @param max_disbursements_amount Filter for all amounts less than a value.
#' @param max_total_contributions Filter for all amounts less than a value.
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param amendment_indicator Amendent types: -N new -A amendment -T terminated -C consolidated -M multi-candidate -S secondary NULL might be new or amendment. If amendment indicator is null and the filings is the first or first in a chain treat it as if it was a new. If it is not the first or first in a chain then treat the filing as an amendment.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param max_receipts_amount Filter for all amounts less than a value.
#' @param is_amended False indicates that a report is the most recent. True indicates that the report has been superseded by an amendment.
#' @param min_disbursements_amount Filter for all amounts greater than a value.
#' @param min_receipts_amount Filter for all amounts greater than a value.
#' @param candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param beginning_image_number Unique identifier for the electronic or paper report. This number is used to construct PDF URLs to the original document.
#' @param sort Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param report_type Report type; prefix with "-" to exclude. Name of report where the underlying data comes from: - 10D Pre-Election - 10G Pre-General - 10P Pre-Primary - 10R Pre-Run-Off - 10S Pre-Special - 12C Pre-Convention - 12G Pre-General - 12P Pre-Primary - 12R Pre-Run-Off - 12S Pre-Special - 30D Post-Election - 30G Post-General - 30P Post-Primary - 30R Post-Run-Off - 30S Post-Special - 60D Post-Convention - M1 January Monthly - M10 October Monthly - M11 November Monthly - M12 December Monthly - M2 February Monthly - M3 March Monthly - M4 April Monthly - M5 May Monthly - M6 June Monthly - M7 July Monthly - M8 August Monthly - M9 September Monthly - MY Mid-Year Report - Q1 April Quarterly - Q2 July Quarterly - Q3 October Quarterly - TER Termination Report - YE Year-End - ADJ COMP ADJUST AMEND - CA COMPREHENSIVE AMEND
#' @param most_recent Report is either new or is the most-recently filed amendment
#' @param entity_type Committee groupings based on FEC filing form. Choose one of: `presidential`, `pac-party`, `house-senate`, or `ie-only`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_reports_entity_type <- function(min_debts_owed_amount, max_debts_owed_expenditures, sort_hide_null, year, max_cash_on_hand_end_period_amount, filer_type, max_party_coordinated_expenditures, q_spender, max_receipt_date, per_page, max_independent_expenditures, min_party_coordinated_expenditures, committee_type, page, min_total_contributions, min_cash_on_hand_end_period_amount, min_receipt_date, sort_null_only, min_independent_expenditures, q_filer, max_disbursements_amount, max_total_contributions, cycle, amendment_indicator, sort_nulls_last, max_receipts_amount, is_amended, min_disbursements_amount, min_receipts_amount, candidate_id, beginning_image_number, sort, committee_id, report_type, most_recent, entity_type, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/reports/{entity_type}/", entity_type = entity_type),
    method = "get",
    api_key = api_key,
    query = list(min_debts_owed_amount = min_debts_owed_amount, max_debts_owed_expenditures = max_debts_owed_expenditures, sort_hide_null = sort_hide_null, year = year, max_cash_on_hand_end_period_amount = max_cash_on_hand_end_period_amount, filer_type = filer_type, max_party_coordinated_expenditures = max_party_coordinated_expenditures, q_spender = q_spender, max_receipt_date = max_receipt_date, per_page = per_page, max_independent_expenditures = max_independent_expenditures, min_party_coordinated_expenditures = min_party_coordinated_expenditures, committee_type = committee_type, page = page, min_total_contributions = min_total_contributions, min_cash_on_hand_end_period_amount = min_cash_on_hand_end_period_amount, min_receipt_date = min_receipt_date, sort_null_only = sort_null_only, min_independent_expenditures = min_independent_expenditures, q_filer = q_filer, max_disbursements_amount = max_disbursements_amount, max_total_contributions = max_total_contributions, cycle = cycle, amendment_indicator = amendment_indicator, sort_nulls_last = sort_nulls_last, max_receipts_amount = max_receipts_amount, is_amended = is_amended, min_disbursements_amount = min_disbursements_amount, min_receipts_amount = min_receipts_amount, candidate_id = candidate_id, beginning_image_number = beginning_image_number, sort = sort, committee_id = committee_id, report_type = report_type, most_recent = most_recent)
  )
}

#' Get totals by entity
#'
#' Provides cumulative receipt totals by entity type, over a two year cycle. Totals are adjusted to avoid double counting. This is [the sql](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V41__large_aggregates.sql) that creates these calculations.
#'
#' @inheritParams fec_call_api
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param page For paginating through results, starting at page 1
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_totals_by_entity <- function(cycle, sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/totals/by_entity/",
    method = "get",
    api_key = api_key,
    query = list(cycle = cycle, sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, page = page)
  )
}

#' Get totals entity type
#'
#' This endpoint provides information about a committee's Form 3, Form 3X, or Form 3P financial reports, which are aggregated by two-year period. We refer to two-year periods as a `cycle`. The cycle is named after the even-numbered year and includes the year before it. To obtain totals from 2013 and 2014, you would use 2014. In odd-numbered years, the current cycle is the next year — for example, in 2015, the current cycle is 2016. For presidential and Senate candidates, multiple two-year cycles exist between elections.
#'
#' @inheritParams fec_call_api
#' @param max_first_f1_date Filter for committees whose first Form 1 was received on or before this date.
#' @param min_receipts Filter for all amounts greater than a value.
#' @param cycle Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year.
#' @param filing_frequency The one-letter code of the filing frequency: - A Administratively terminated - D Debt - M Monthly filer - Q Quarterly filer - T Terminated - W Waived
#' @param max_receipts Filter for all amounts less than a value.
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort_nulls_last Toggle that sorts null values last
#' @param min_last_debts_owed_by_committee Filter for all amounts greater than a value.
#' @param max_last_cash_on_hand_end_period Filter for all amounts less than a value.
#' @param treasurer_name Name of the Committee's treasurer. If multiple treasurers for the committee, the most recent treasurer will be shown.
#' @param sponsor_candidate_id A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. This is a filter for Leadership PAC sponsor.
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param max_disbursements Filter for all amounts less than a value.
#' @param committee_state US state or territory
#' @param committee_type The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param page For paginating through results, starting at page 1
#' @param max_last_debts_owed_by_committee Filter for all amounts less than a value.
#' @param committee_id A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param committee_designation The one-letter designation code of the organization: - A authorized by a candidate - J joint fundraising committee - P principal campaign committee of a candidate - U unauthorized - B lobbyist/registrant PAC - D leadership PAC
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param min_first_f1_date Filter for committees whose first Form 1 was received on or after this date.
#' @param organization_type The one-letter code for the kind for organization: - C corporation - L labor organization - M membership organization - T trade association - V cooperative - W corporation without capital stock
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param min_disbursements Filter for all amounts greater than a value.
#' @param min_last_cash_on_hand_end_period Filter for all amounts greater than a value.
#' @param entity_type Committee groupings based on FEC filing form. Choose one of: `presidential`, `pac`, `party`, `pac-party`, `house-senate`, or `ie-only`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_totals_entity_type <- function(max_first_f1_date, min_receipts, cycle, filing_frequency, max_receipts, sort_hide_null, sort_nulls_last, min_last_debts_owed_by_committee, max_last_cash_on_hand_end_period, treasurer_name, sponsor_candidate_id, per_page, max_disbursements, committee_state, committee_type, page, max_last_debts_owed_by_committee, committee_id, committee_designation, sort_null_only, min_first_f1_date, organization_type, sort, min_disbursements, min_last_cash_on_hand_end_period, entity_type, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = c("/totals/{entity_type}/", entity_type = entity_type),
    method = "get",
    api_key = api_key,
    query = list(max_first_f1_date = max_first_f1_date, min_receipts = min_receipts, cycle = cycle, filing_frequency = filing_frequency, max_receipts = max_receipts, sort_hide_null = sort_hide_null, sort_nulls_last = sort_nulls_last, min_last_debts_owed_by_committee = min_last_debts_owed_by_committee, max_last_cash_on_hand_end_period = max_last_cash_on_hand_end_period, treasurer_name = treasurer_name, sponsor_candidate_id = sponsor_candidate_id, per_page = per_page, max_disbursements = max_disbursements, committee_state = committee_state, committee_type = committee_type, page = page, max_last_debts_owed_by_committee = max_last_debts_owed_by_committee, committee_id = committee_id, committee_designation = committee_designation, sort_null_only = sort_null_only, min_first_f1_date = min_first_f1_date, organization_type = organization_type, sort = sort, min_disbursements = min_disbursements, min_last_cash_on_hand_end_period = min_last_cash_on_hand_end_period)
  )
}
