# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get calendar dates
#'
#' Combines the election and reporting dates with Commission meetings, conferences, outreach, Advisory Opinions, rules, litigation dates and other events into one calendar. State and report type filtering is no longer available.
#'
#' @inheritParams fec_call_api
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param min_start_date The minimum start date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param calendar_category_id Each type of event has a calendar category with an integer id. Options are: Open Meetings: 32, Executive Sessions: 39, Public Hearings: 40, Conferences: 33, Roundtables: 34, Election Dates: 36, Federal Holidays: 37, FEA Periods: 38, Commission Meetings: 20, Reporting Deadlines: 21, Conferences and Outreach: 22, AOs and Rules: 23, Other: 24, Quarterly: 25, Monthly: 26, Pre and Post-Elections: 27, EC Periods:28, and IE Periods: 29
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param min_end_date The minimum end date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param event_id An unique ID for an event. Useful for downloading a single event to your calendar. This ID is not a permanent, persistent ID.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param description Brief description of event
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param max_end_date The maximum end date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param summary Longer description of event
#' @param max_start_date The maximum start date.(MM/DD/YYYY or YYYY-MM-DD)
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_calendar_dates <- function(sort_nulls_last, page, min_start_date, calendar_category_id, sort_hide_null, min_end_date, event_id, sort_null_only, per_page, description, sort, max_end_date, summary, max_start_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/calendar-dates/",
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, page = page, min_start_date = min_start_date, calendar_category_id = calendar_category_id, sort_hide_null = sort_hide_null, min_end_date = min_end_date, event_id = event_id, sort_null_only = sort_null_only, per_page = per_page, description = description, sort = sort, max_end_date = max_end_date, summary = summary, max_start_date = max_start_date)
  )
}

#' Get calendar dates export
#'
#' Returns CSV or ICS for downloading directly into calendar applications like Google, Outlook or other applications. Combines the election and reporting dates with Commission meetings, conferences, outreach, Advisory Opinions, rules, litigation dates and other events into one calendar. State filtering now applies to elections, reports and reporting periods. Presidential pre-primary report due dates are not shown on even years. Filers generally opt to file monthly rather than submit over 50 pre-primary election reports. All reporting deadlines are available at /reporting-dates/ for reference. This is [the sql function](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V40__omnibus_dates.sql) that creates the calendar.
#'
#' @inheritParams fec_call_api
#' @param renderer BKTODO: No description provided.
#' @param sort_nulls_last Toggle that sorts null values last
#' @param page For paginating through results, starting at page 1
#' @param min_start_date The minimum start date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param calendar_category_id Each type of event has a calendar category with an integer id. Options are: Open Meetings: 32, Executive Sessions: 39, Public Hearings: 40, Conferences: 33, Roundtables: 34, Election Dates: 36, Federal Holidays: 37, FEA Periods: 38, Commission Meetings: 20, Reporting Deadlines: 21, Conferences and Outreach: 22, AOs and Rules: 23, Other: 24, Quarterly: 25, Monthly: 26, Pre and Post-Elections: 27, EC Periods:28, and IE Periods: 29
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param min_end_date The minimum end date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param event_id An unique ID for an event. Useful for downloading a single event to your calendar. This ID is not a permanent, persistent ID.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param description Brief description of event
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param max_end_date The maximum end date.(MM/DD/YYYY or YYYY-MM-DD)
#' @param summary Longer description of event
#' @param max_start_date The maximum start date.(MM/DD/YYYY or YYYY-MM-DD)
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_calendar_dates_export <- function(renderer, sort_nulls_last, page, min_start_date, calendar_category_id, sort_hide_null, min_end_date, event_id, sort_null_only, per_page, description, sort, max_end_date, summary, max_start_date, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/calendar-dates/export/",
    method = "get",
    api_key = api_key,
    query = list(renderer = renderer, sort_nulls_last = sort_nulls_last, page = page, min_start_date = min_start_date, calendar_category_id = calendar_category_id, sort_hide_null = sort_hide_null, min_end_date = min_end_date, event_id = event_id, sort_null_only = sort_null_only, per_page = per_page, description = description, sort = sort, max_end_date = max_end_date, summary = summary, max_start_date = max_start_date)
  )
}

#' Get election dates
#'
#' FEC election dates since 1995.
#'
#' @inheritParams fec_call_api
#' @param max_update_date The maximum date this record was last updated.(MM/DD/YYYY or YYYY-MM-DD)
#' @param sort_nulls_last Toggle that sorts null values last
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param max_primary_general_date The maximum date of primary or general election.(MM/DD/YYYY or YYYY-MM-DD)
#' @param min_update_date The minimum date this record was last updated.(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_create_date The maximum date this record was added to the system.(MM/DD/YYYY or YYYY-MM-DD)
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param min_election_date The minimum date of election.
#' @param election_party Party, if applicable.
#' @param election_type_id Election type id
#' @param page For paginating through results, starting at page 1
#' @param min_create_date The minimum date this record was added to the system.(MM/DD/YYYY or YYYY-MM-DD)
#' @param min_primary_general_date The minimum date of primary or general election.(MM/DD/YYYY or YYYY-MM-DD)
#' @param election_year Year of election
#' @param election_district House district of the office sought, if applicable.
#' @param office_sought House, Senate or presidential office.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param max_election_date The maximum date of election.
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param election_state State or territory of the office sought.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_election_dates <- function(max_update_date, sort_nulls_last, sort_hide_null, max_primary_general_date, min_update_date, max_create_date, per_page, min_election_date, election_party, election_type_id, page, min_create_date, min_primary_general_date, election_year, election_district, office_sought, sort_null_only, max_election_date, sort, election_state, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/election-dates/",
    method = "get",
    api_key = api_key,
    query = list(max_update_date = max_update_date, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, max_primary_general_date = max_primary_general_date, min_update_date = min_update_date, max_create_date = max_create_date, per_page = per_page, min_election_date = min_election_date, election_party = election_party, election_type_id = election_type_id, page = page, min_create_date = min_create_date, min_primary_general_date = min_primary_general_date, election_year = election_year, election_district = election_district, office_sought = office_sought, sort_null_only = sort_null_only, max_election_date = max_election_date, sort = sort, election_state = election_state)
  )
}

#' Get reporting dates
#'
#' FEC election dates since 1995.
#'
#' @inheritParams fec_call_api
#' @param max_update_date The maximum date this record was last updated.(MM/DD/YYYY or YYYY-MM-DD)
#' @param page For paginating through results, starting at page 1
#' @param max_due_date The maximum date the report is due.(MM/DD/YYYY or YYYY-MM-DD)
#' @param min_create_date The minimum date this record was added to the system.(MM/DD/YYYY or YYYY-MM-DD)
#' @param min_due_date The minimum date the report is due.(MM/DD/YYYY or YYYY-MM-DD)
#' @param sort_hide_null Hide null values on sorted column(s).
#' @param sort_nulls_last Toggle that sorts null values last
#' @param min_update_date The minimum date this record was last updated.(MM/DD/YYYY or YYYY-MM-DD)
#' @param max_create_date The maximum date this record was added to the system.(MM/DD/YYYY or YYYY-MM-DD)
#' @param per_page The number of results returned per page. Defaults to 20.
#' @param sort_null_only Toggle that filters out all rows having sort column that is non-null
#' @param sort Provide a field to sort by. Use `-` for descending order.
#' @param report_year Forms with coverage date - year from the coverage ending date. Forms without coverage date - year from the receipt date.
#' @param report_type Name of report where the underlying data comes from: - 10D Pre-Election - 10G Pre-General - 10P Pre-Primary - 10R Pre-Run-Off - 10S Pre-Special - 12C Pre-Convention - 12G Pre-General - 12P Pre-Primary - 12R Pre-Run-Off - 12S Pre-Special - 30D Post-Election - 30G Post-General - 30P Post-Primary - 30R Post-Run-Off - 30S Post-Special - 60D Post-Convention - M1 January Monthly - M10 October Monthly - M11 November Monthly - M12 December Monthly - M2 February Monthly - M3 March Monthly - M4 April Monthly - M5 May Monthly - M6 June Monthly - M7 July Monthly - M8 August Monthly - M9 September Monthly - MY Mid-Year Report - Q1 April Quarterly - Q2 July Quarterly - Q3 October Quarterly - TER Termination Report - YE Year-End - ADJ COMP ADJUST AMEND - CA COMPREHENSIVE AMEND - 90S Post Inaugural Supplement - 90D Post Inaugural - 48 48 Hour Notification - 24 24 Hour Notification - M7S July Monthly/Semi-Annual - MSA Monthly Semi-Annual (MY) - MYS Monthly Year End/Semi-Annual - Q2S July Quarterly/Semi-Annual - QSA Quarterly Semi-Annual (MY) - QYS Quarterly Year End/Semi-Annual - QYE Quarterly Semi-Annual (YE) - QMS Quarterly Mid-Year/ Semi-Annual - MSY Monthly Semi-Annual (YE)
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
fec_get_reporting_dates <- function(max_update_date, page, max_due_date, min_create_date, min_due_date, sort_hide_null, sort_nulls_last, min_update_date, max_create_date, per_page, sort_null_only, sort, report_year, report_type, api_key = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) {
  fec_call_api(
    path = "/reporting-dates/",
    method = "get",
    api_key = api_key,
    query = list(max_update_date = max_update_date, page = page, max_due_date = max_due_date, min_create_date = min_create_date, min_due_date = min_due_date, sort_hide_null = sort_hide_null, sort_nulls_last = sort_nulls_last, min_update_date = min_update_date, max_create_date = max_create_date, per_page = per_page, sort_null_only = sort_null_only, sort = sort, report_year = report_year, report_type = report_type)
  )
}
